### ISSUE TITLE
Custom key reminder message

### ISSUE THREAD

**Issue by Dupond** [TheAMM/mpv_crop_script#2]
Hello,
Thanx for your great script !
It would be nice if the key reminder displayed when you launch the script was configurable, so that we could translate it. Would there be a way to customize it in the config file ?
Also, you use capital letters in this message, whereas the pre-configured keys are lower-case letters : eg. `fmt_key("D", "Autodetect crop")` should be `fmt_key("d", "Autodetect crop")` It gives the impression that the script doesn't work, since pressing "D" does nothing.
Best regards,
Dupond

**Comment by TheAMM** [comment]
You can edit your copy of the script. I'm not going to i18n my scripts, especially not in user config.
I use the format `SHIFT+X` in my other scripts, since lowercase letters look stupid outside configuration. Again, you may edit your copy of the script.
