### ISSUE TITLE
Why not use mpv's native read_options ?

### ISSUE THREAD

**Issue by Dupond** [TheAMM/mpv_crop_script#4]
Hello,
I was wondering why the entire logic for `read_options` is reimplemented in the script, instead of using mpv's ?
Best regards,
Dupond

**Comment by TheAMM** [comment]
Because mine can do more.

**Comment by TheAMM** [comment]
Github issues are meant for issues, not asking about implementation details (especially when the file itself tells you what OptionParser can do). This is something you should casually ask on IRC or something.
Cease with the attitude.

**Comment by Dupond** [comment]
Well, this might have been an issue if you didn't know about mpv's read_options. Anyway, since you don't seem to be ready to listen to any observation about your script, I'll stop bothering you. It's clearly the impression that you give, but this doesn't excuse your rude words (and it's not the first time).
Please cease with the attitude. You're clearly not a respectful person, so indeed you don't deserve any more time talking to you. This is simply a shame... but you can't force anyone to be polite and respectful, right ? So I give up, and that's all. At least I have tried !

**Comment by TheAMM** [comment]
It's disrespectful to question code decisions or my knowledge about `read_options` when the release and commit logs both explicitly mention moving over to the new option parser.
I have used no rude words, and respect is earned, not given. "thanx" and pseudo-intellectually signing off on posts has dipped you below the baseline, though.
I don't know what you have tried, but I'll gladly be done with this if you get this uppity over a cold tone in responses to questions that don't seem to know their place.
